### ISSUE TITLE
Add error message or type checking for async render callback.

### ISSUE THREAD

**Issue by KylerHansen** [electrovir/element-vir#14]
It would be helpful if an error gets thrown or the type checker catches it when you make the renderCallback asynchronous. 
`
    async renderCallback ({state, updateState, inputs}) {...
` 

If you do this you get an [object Promise] but no errors are thrown explaining what [object Promise] means.

**Comment by electrovir** [comment]
Fixed in 69b7b5e47227e849c8f7b43485d72a4bd2b5d84d
