### ISSUE TITLE
Better error messaging when "assign" is used incorrectly.

### ISSUE THREAD

**Issue by jalenmmorgan** [electrovir/element-vir#18]
I had an error where it was saying I forgot to assign an input. I was going crazy trying to figure out where the issue was. I was assigning the input in my code. Took me about 10 minutes to figure out I typed it wrong.

What I should've typed: 
`${assign(HabitItem, {habit: inputs.habit})}`

What I actually typed:
`${assign(HabitItem), {habit: inputs.habit}}`

**Comment by electrovir** [comment]
Nice catch. I modified the type signature of `assign` so that it'll be a TS error if the only input looks like it's meant to be a custom element. This will be included in the next release.
